import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const palette = JSON.parse(readFileSync(resolve(root, 'palette.json'), 'utf8'));
const tokens = palette.rararulab;

// ── Web: CSS custom properties ──

function buildCSS() {
  const colors = tokens.color;
  const ansi = tokens.ansi;
  const typo = tokens.typography;
  const spacing = tokens.spacing;
  const radius = tokens.radius;
  const motion = tokens.motion;

  let css = '/* Generated by @rararulab/style — do not edit */\n:root {\n';

  // Colors
  for (const [k, v] of Object.entries(colors)) {
    css += `  --color-${k}: ${v.$value};\n`;
  }
  css += '\n';

  // Typography
  for (const [k, v] of Object.entries(typo.family)) {
    css += `  --font-${k}: ${v.$value};\n`;
  }
  for (const [k, v] of Object.entries(typo.size)) {
    css += `  --text-${k}: ${v.$value};\n`;
  }
  for (const [k, v] of Object.entries(typo.weight)) {
    css += `  --font-${k}: ${v.$value};\n`;
  }
  for (const [k, v] of Object.entries(typo.leading)) {
    css += `  --leading-${k}: ${v.$value};\n`;
  }
  css += '\n';

  // Spacing
  for (const [k, v] of Object.entries(spacing)) {
    css += `  --space-${k}: ${v.$value};\n`;
  }
  css += '\n';

  // Radius
  for (const [k, v] of Object.entries(radius)) {
    css += `  --radius-${k}: ${v.$value};\n`;
  }
  css += '\n';

  // Motion
  for (const [k, v] of Object.entries(motion)) {
    css += `  --motion-${k}: ${v.$value};\n`;
  }

  css += '}\n';

  mkdirSync(resolve(root, 'platforms/web'), { recursive: true });
  writeFileSync(resolve(root, 'platforms/web/tokens.css'), css);
  console.log('  ✓ platforms/web/tokens.css');
}

// ── Terminal: ANSI JSON + Alacritty TOML ──

function buildTerminal() {
  const ansi = tokens.ansi;
  const dir = resolve(root, 'platforms/terminal');
  mkdirSync(dir, { recursive: true });

  // ANSI JSON
  const ansiMap = {};
  for (const [k, v] of Object.entries(ansi)) {
    ansiMap[k] = v.$value;
  }
  ansiMap.foreground = tokens.color.ink.$value;
  ansiMap.background = tokens.color.bg.$value;
  writeFileSync(resolve(dir, 'ansi.json'), JSON.stringify(ansiMap, null, 2) + '\n');
  console.log('  ✓ platforms/terminal/ansi.json');

  // Alacritty TOML
  let toml = '# Generated by @rararulab/style — do not edit\n\n[colors.primary]\n';
  toml += `background = "${tokens.color.bg.$value}"\n`;
  toml += `foreground = "${tokens.color.ink.$value}"\n\n`;
  toml += '[colors.normal]\n';
  for (const name of ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white']) {
    toml += `${name} = "${ansi[name].$value}"\n`;
  }
  toml += '\n[colors.bright]\n';
  for (const name of ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white']) {
    toml += `${name} = "${ansi[`bright-${name}`].$value}"\n`;
  }
  writeFileSync(resolve(dir, 'alacritty.toml'), toml);
  console.log('  ✓ platforms/terminal/alacritty.toml');
}

// ── TUI: Ratatui Rust theme ──

function buildTUI() {
  const colors = tokens.color;
  const ansi = tokens.ansi;
  const dir = resolve(root, 'platforms/tui');
  mkdirSync(dir, { recursive: true });

  let rs = `// Generated by @rararulab/style — do not edit
use ratatui::style::Color;

pub const INK: Color = Color::Rgb(${hexToRGB(colors.ink.$value)});
pub const MUTED: Color = Color::Rgb(${hexToRGB(colors.muted.$value)});
pub const SUBTLE: Color = Color::Rgb(${hexToRGB(colors.subtle.$value)});
pub const LINE: Color = Color::Rgb(${hexToRGB(colors.line.$value)});
pub const SURFACE: Color = Color::Rgb(${hexToRGB(colors.surface.$value)});
pub const BG: Color = Color::Rgb(${hexToRGB(colors.bg.$value)});
pub const POP: Color = Color::Rgb(${hexToRGB(colors.pop.$value)});
pub const OK: Color = Color::Rgb(${hexToRGB(colors.ok.$value)});
pub const WARN: Color = Color::Rgb(${hexToRGB(colors.warn.$value)});
pub const ERR: Color = Color::Rgb(${hexToRGB(colors.err.$value)});
`;

  writeFileSync(resolve(dir, 'theme.rs'), rs);
  console.log('  ✓ platforms/tui/theme.rs');
}

// ── CLI: ANSI escape code helpers (Rust) ──

function buildCLI() {
  const colors = tokens.color;
  const dir = resolve(root, 'platforms/cli');
  mkdirSync(dir, { recursive: true });

  let rs = `// Generated by @rararulab/style — do not edit
// Usage: print!("{}{}{}", style::POP, "highlighted text", style::RESET);

pub const RESET: &str = "\\x1b[0m";
pub const BOLD: &str = "\\x1b[1m";
pub const DIM: &str = "\\x1b[2m";

pub const INK: &str = "\\x1b[38;2;${hexToRGBSemicolon(colors.ink.$value)}m";
pub const MUTED: &str = "\\x1b[38;2;${hexToRGBSemicolon(colors.muted.$value)}m";
pub const POP: &str = "\\x1b[38;2;${hexToRGBSemicolon(colors.pop.$value)}m";
pub const OK: &str = "\\x1b[38;2;${hexToRGBSemicolon(colors.ok.$value)}m";
pub const WARN: &str = "\\x1b[38;2;${hexToRGBSemicolon(colors.warn.$value)}m";
pub const ERR: &str = "\\x1b[38;2;${hexToRGBSemicolon(colors.err.$value)}m";

pub const BG_POP: &str = "\\x1b[48;2;${hexToRGBSemicolon(colors.pop.$value)}m";
pub const BG_OK: &str = "\\x1b[48;2;${hexToRGBSemicolon(colors.ok.$value)}m";
pub const BG_WARN: &str = "\\x1b[48;2;${hexToRGBSemicolon(colors.warn.$value)}m";
pub const BG_ERR: &str = "\\x1b[48;2;${hexToRGBSemicolon(colors.err.$value)}m";
`;

  writeFileSync(resolve(dir, 'theme.rs'), rs);
  console.log('  ✓ platforms/cli/theme.rs');
}

// ── Helpers ──

function hexToRGB(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `${r}, ${g}, ${b}`;
}

function hexToRGBSemicolon(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `${r};${g};${b}`;
}

// ── Run ──

console.log('@rararulab/style build:');
buildCSS();
buildTerminal();
buildTUI();
buildCLI();
console.log('\nDone.');
