import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

interface Token {
  $value: string | number;
  $type?: string;
  $description?: string;
}

interface TokenGroup {
  [key: string]: Token | TokenGroup | string;
}

interface Palette {
  rararulab: {
    color: Record<string, Token>;
    ansi: Record<string, Token | string>;
    typography: {
      family: Record<string, Token>;
      size: Record<string, Token>;
      weight: Record<string, Token>;
      leading: Record<string, Token>;
    };
    spacing: Record<string, Token>;
    radius: Record<string, Token>;
    motion: Record<string, Token>;
  };
}

const palette: Palette = JSON.parse(readFileSync(resolve(root, 'palette.json'), 'utf8'));
const tokens = palette.rararulab;

// ── Helpers ──

function hexToRGB(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `${r}, ${g}, ${b}`;
}

function hexToRGBSemicolon(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `${r};${g};${b}`;
}

// ── Web: CSS custom properties ──

function buildCSS(): void {
  const { color, typography: typo, spacing, radius, motion } = tokens;

  let css = '/* Generated by @rararulab/style — do not edit */\n:root {\n';

  for (const [k, v] of Object.entries(color)) {
    css += `  --color-${k}: ${v.$value};\n`;
  }
  css += '\n';

  for (const [k, v] of Object.entries(typo.family)) {
    css += `  --font-${k}: ${v.$value};\n`;
  }
  for (const [k, v] of Object.entries(typo.size)) {
    css += `  --text-${k}: ${v.$value};\n`;
  }
  for (const [k, v] of Object.entries(typo.weight)) {
    css += `  --font-${k}: ${v.$value};\n`;
  }
  for (const [k, v] of Object.entries(typo.leading)) {
    css += `  --leading-${k}: ${v.$value};\n`;
  }
  css += '\n';

  for (const [k, v] of Object.entries(spacing)) {
    css += `  --space-${k}: ${v.$value};\n`;
  }
  css += '\n';

  for (const [k, v] of Object.entries(radius)) {
    css += `  --radius-${k}: ${v.$value};\n`;
  }
  css += '\n';

  for (const [k, v] of Object.entries(motion)) {
    css += `  --motion-${k}: ${v.$value};\n`;
  }

  css += '}\n';

  mkdirSync(resolve(root, 'platforms/web'), { recursive: true });
  writeFileSync(resolve(root, 'platforms/web/tokens.css'), css);
  console.log('  ✓ platforms/web/tokens.css');
}

// ── Terminal: ANSI JSON + Alacritty TOML ──

function buildTerminal(): void {
  const ansi = tokens.ansi;
  const dir = resolve(root, 'platforms/terminal');
  mkdirSync(dir, { recursive: true });

  const ansiMap: Record<string, string> = {};
  for (const [k, v] of Object.entries(ansi)) {
    if (typeof v === 'object' && '$value' in v) {
      ansiMap[k] = v.$value as string;
    }
  }
  ansiMap.foreground = tokens.color.ink.$value as string;
  ansiMap.background = tokens.color.bg.$value as string;
  writeFileSync(resolve(dir, 'ansi.json'), JSON.stringify(ansiMap, null, 2) + '\n');
  console.log('  ✓ platforms/terminal/ansi.json');

  const ansiColors = [
    'black',
    'red',
    'green',
    'yellow',
    'blue',
    'magenta',
    'cyan',
    'white',
  ] as const;

  let toml = '# Generated by @rararulab/style — do not edit\n\n[colors.primary]\n';
  toml += `background = "${tokens.color.bg.$value}"\n`;
  toml += `foreground = "${tokens.color.ink.$value}"\n\n`;
  toml += '[colors.normal]\n';
  for (const name of ansiColors) {
    toml += `${name} = "${(ansi[name] as Token).$value}"\n`;
  }
  toml += '\n[colors.bright]\n';
  for (const name of ansiColors) {
    toml += `${name} = "${(ansi[`bright-${name}`] as Token).$value}"\n`;
  }
  writeFileSync(resolve(dir, 'alacritty.toml'), toml);
  console.log('  ✓ platforms/terminal/alacritty.toml');
}

// ── TUI: Ratatui Rust theme ──

function buildTUI(): void {
  const { color } = tokens;
  const dir = resolve(root, 'platforms/tui');
  mkdirSync(dir, { recursive: true });

  const rs = `// Generated by @rararulab/style — do not edit
use ratatui::style::Color;

pub const INK: Color = Color::Rgb(${hexToRGB(color.ink.$value as string)});
pub const MUTED: Color = Color::Rgb(${hexToRGB(color.muted.$value as string)});
pub const SUBTLE: Color = Color::Rgb(${hexToRGB(color.subtle.$value as string)});
pub const LINE: Color = Color::Rgb(${hexToRGB(color.line.$value as string)});
pub const SURFACE: Color = Color::Rgb(${hexToRGB(color.surface.$value as string)});
pub const BG: Color = Color::Rgb(${hexToRGB(color.bg.$value as string)});
pub const POP: Color = Color::Rgb(${hexToRGB(color.pop.$value as string)});
pub const OK: Color = Color::Rgb(${hexToRGB(color.ok.$value as string)});
pub const WARN: Color = Color::Rgb(${hexToRGB(color.warn.$value as string)});
pub const ERR: Color = Color::Rgb(${hexToRGB(color.err.$value as string)});
`;

  writeFileSync(resolve(dir, 'theme.rs'), rs);
  console.log('  ✓ platforms/tui/theme.rs');
}

// ── CLI: ANSI escape code helpers (Rust) ──

function buildCLI(): void {
  const { color } = tokens;
  const dir = resolve(root, 'platforms/cli');
  mkdirSync(dir, { recursive: true });

  const rs = `// Generated by @rararulab/style — do not edit
// Usage: print!("{}{}{}", style::POP, "highlighted text", style::RESET);

pub const RESET: &str = "\\x1b[0m";
pub const BOLD: &str = "\\x1b[1m";
pub const DIM: &str = "\\x1b[2m";

pub const INK: &str = "\\x1b[38;2;${hexToRGBSemicolon(color.ink.$value as string)}m";
pub const MUTED: &str = "\\x1b[38;2;${hexToRGBSemicolon(color.muted.$value as string)}m";
pub const POP: &str = "\\x1b[38;2;${hexToRGBSemicolon(color.pop.$value as string)}m";
pub const OK: &str = "\\x1b[38;2;${hexToRGBSemicolon(color.ok.$value as string)}m";
pub const WARN: &str = "\\x1b[38;2;${hexToRGBSemicolon(color.warn.$value as string)}m";
pub const ERR: &str = "\\x1b[38;2;${hexToRGBSemicolon(color.err.$value as string)}m";

pub const BG_POP: &str = "\\x1b[48;2;${hexToRGBSemicolon(color.pop.$value as string)}m";
pub const BG_OK: &str = "\\x1b[48;2;${hexToRGBSemicolon(color.ok.$value as string)}m";
pub const BG_WARN: &str = "\\x1b[48;2;${hexToRGBSemicolon(color.warn.$value as string)}m";
pub const BG_ERR: &str = "\\x1b[48;2;${hexToRGBSemicolon(color.err.$value as string)}m";
`;

  writeFileSync(resolve(dir, 'theme.rs'), rs);
  console.log('  ✓ platforms/cli/theme.rs');
}

// ── Pages: style showcase ──

function buildPages(): void {
  const { color, ansi, typography, spacing, radius, motion } = tokens;
  const dir = resolve(root, 'docs');
  mkdirSync(dir, { recursive: true });

  const colorSwatches = Object.entries(color)
    .map(
      ([name, t]) =>
        `<div class="swatch">
        <div class="swatch-block" style="background:${t.$value}"></div>
        <code>${name}</code>
        <span class="hex">${t.$value}</span>
      </div>`,
    )
    .join('\n      ');

  const ansiSwatches = Object.entries(ansi)
    .filter(([, v]) => typeof v === 'object')
    .map(
      ([name, t]) =>
        `<div class="swatch">
        <div class="swatch-block" style="background:${(t as Token).$value}"></div>
        <code>${name}</code>
        <span class="hex">${(t as Token).$value}</span>
      </div>`,
    )
    .join('\n      ');

  const typeScale = Object.entries(typography.size)
    .map(
      ([name, t]) =>
        `<div class="type-row">
        <code class="type-label">text-${name}</code>
        <span style="font-size:${t.$value}">The quick brown fox</span>
      </div>`,
    )
    .join('\n      ');

  const spacingScale = Object.entries(spacing)
    .map(
      ([name, t]) =>
        `<div class="space-row">
        <code>space-${name}</code>
        <div class="space-bar" style="width:${t.$value === '0' ? '2px' : t.$value}"></div>
        <span class="hex">${t.$value}</span>
      </div>`,
    )
    .join('\n      ');

  const radiusScale = Object.entries(radius)
    .map(
      ([name, t]) =>
        `<div class="radius-item">
        <div class="radius-block" style="border-radius:${t.$value}"></div>
        <code>${name}</code>
        <span class="hex">${t.$value}</span>
      </div>`,
    )
    .join('\n      ');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@rararulab/style</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
    :root {
      --bg: #fafafa; --surface: #fff; --ink: #111; --muted: #666;
      --line: #e2e2e2; --pop: #4A8FE2; --radius: 8px;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Inter', system-ui, sans-serif;
      background: var(--bg); color: var(--ink);
      line-height: 1.6; font-size: 16px;
    }
    .container { max-width: 960px; margin: 0 auto; padding: 0 24px; }

    /* header */
    header { padding: 48px 0 40px; border-bottom: 1px solid var(--line); }
    header h1 { font-size: 2.4rem; font-weight: 700; letter-spacing: -0.03em; }
    header p { color: var(--muted); margin-top: 8px; font-size: 1.05rem; }
    .badge {
      display: inline-block; margin-top: 16px; padding: 4px 12px;
      background: var(--ink); color: #fff; border-radius: 4px;
      font-family: 'JetBrains Mono', monospace; font-size: 0.8rem;
    }

    /* sections */
    section { padding: 48px 0; border-bottom: 1px solid var(--line); }
    section:last-child { border-bottom: none; }
    h2 {
      font-size: 1.4rem; font-weight: 600; letter-spacing: -0.02em;
      margin-bottom: 24px; display: flex; align-items: center; gap: 10px;
    }
    h2 .num { color: var(--pop); font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; }

    /* swatches */
    .swatch-grid {
      display: grid; grid-template-columns: repeat(auto-fill, minmax(120px, 1fr)); gap: 12px;
    }
    .swatch { text-align: center; }
    .swatch-block {
      width: 100%; aspect-ratio: 1; border-radius: var(--radius);
      border: 1px solid var(--line);
    }
    .swatch code {
      display: block; margin-top: 8px; font-size: 0.8rem; font-weight: 600;
      font-family: 'JetBrains Mono', monospace;
    }
    .swatch .hex { font-size: 0.75rem; color: var(--muted); }

    /* type scale */
    .type-row {
      display: flex; align-items: baseline; gap: 16px;
      padding: 10px 0; border-bottom: 1px solid var(--line);
    }
    .type-row:last-child { border-bottom: none; }
    .type-label {
      width: 80px; flex-shrink: 0; font-size: 0.8rem; color: var(--muted);
      font-family: 'JetBrains Mono', monospace;
    }

    /* spacing */
    .space-row { display: flex; align-items: center; gap: 12px; padding: 6px 0; }
    .space-row code {
      width: 72px; flex-shrink: 0; font-size: 0.8rem;
      font-family: 'JetBrains Mono', monospace;
    }
    .space-bar { height: 12px; background: var(--pop); border-radius: 2px; min-width: 2px; }
    .hex { font-size: 0.75rem; color: var(--muted); }

    /* radius */
    .radius-grid { display: flex; gap: 20px; flex-wrap: wrap; }
    .radius-item { text-align: center; }
    .radius-block {
      width: 64px; height: 64px; background: var(--ink); margin-bottom: 8px;
    }
    .radius-item code {
      display: block; font-size: 0.8rem; font-weight: 600;
      font-family: 'JetBrains Mono', monospace;
    }

    /* platform cards */
    .platform-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .platform-card {
      padding: 20px; border: 1px solid var(--line); border-radius: var(--radius);
      background: var(--surface);
    }
    .platform-card h3 { font-size: 0.95rem; margin-bottom: 8px; }
    .platform-card code {
      font-size: 0.8rem; color: var(--muted); font-family: 'JetBrains Mono', monospace;
    }
    .platform-card pre {
      margin-top: 12px; padding: 12px; background: var(--bg); border-radius: 6px;
      font-size: 0.78rem; overflow-x: auto; line-height: 1.5;
      font-family: 'JetBrains Mono', monospace;
    }

    /* terminal preview */
    .terminal {
      background: #111; color: #e2e2e2; border-radius: var(--radius);
      padding: 16px 20px; font-family: 'JetBrains Mono', monospace;
      font-size: 0.85rem; line-height: 1.8; margin-top: 16px;
    }
    .terminal .prompt { color: #4A8FE2; }
    .terminal .ok { color: #2DA44E; }
    .terminal .warn { color: #D4A015; }
    .terminal .err { color: #CF222E; }
    .terminal .dim { color: #666; }

    footer {
      padding: 24px 0 48px; font-size: 0.85rem; color: var(--muted);
      display: flex; justify-content: space-between;
    }
    footer a { color: var(--ink); text-decoration: none; font-weight: 600; }
    footer a:hover { color: var(--pop); }

    @media (max-width: 640px) {
      .platform-grid { grid-template-columns: 1fr; }
      .swatch-grid { grid-template-columns: repeat(auto-fill, minmax(90px, 1fr)); }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>@rararulab/style</h1>
      <p>Unified design tokens for web, CLI, TUI, and desktop.</p>
      <span class="badge">v${palette.rararulab ? '0.1.0' : '0.0.0'}</span>
    </header>

    <section>
      <h2><span class="num">01</span> Colors</h2>
      <div class="swatch-grid">
        ${colorSwatches}
      </div>
    </section>

    <section>
      <h2><span class="num">02</span> ANSI Terminal</h2>
      <div class="swatch-grid">
        ${ansiSwatches}
      </div>
      <div class="terminal">
        <div><span class="prompt">$</span> rara build</div>
        <div><span class="ok">✓</span> compiled 12 crates in 1.2s</div>
        <div><span class="warn">⚠</span> unused import in lib.rs:14</div>
        <div><span class="err">✗</span> test_parse_date failed</div>
        <div><span class="dim">── 11 passed, 1 failed ──</span></div>
      </div>
    </section>

    <section>
      <h2><span class="num">03</span> Type Scale</h2>
      ${typeScale}
    </section>

    <section>
      <h2><span class="num">04</span> Spacing</h2>
      ${spacingScale}
    </section>

    <section>
      <h2><span class="num">05</span> Radius</h2>
      <div class="radius-grid">
        ${radiusScale}
      </div>
    </section>

    <section>
      <h2><span class="num">06</span> Platform Outputs</h2>
      <div class="platform-grid">
        <div class="platform-card">
          <h3>Web</h3>
          <code>platforms/web/tokens.css</code>
          <pre>color: var(--color-ink);
background: var(--color-bg);
border: 1px solid var(--color-line);</pre>
        </div>
        <div class="platform-card">
          <h3>CLI (Rust)</h3>
          <code>platforms/cli/theme.rs</code>
          <pre>print!("{}Error:{} broke",
  style::ERR, style::RESET);</pre>
        </div>
        <div class="platform-card">
          <h3>TUI / Ratatui</h3>
          <code>platforms/tui/theme.rs</code>
          <pre>let s = Style::default()
  .fg(theme::POP);</pre>
        </div>
        <div class="platform-card">
          <h3>Terminal</h3>
          <code>platforms/terminal/alacritty.toml</code>
          <pre>[colors.normal]
blue = "${(tokens.ansi.blue as Token).$value}"</pre>
        </div>
      </div>
    </section>

    <footer>
      <span>&copy; rararulab</span>
      <a href="https://github.com/rararulab/style">GitHub</a>
    </footer>
  </div>
</body>
</html>`;

  writeFileSync(resolve(dir, 'index.html'), html);
  console.log('  ✓ docs/index.html');
}

// ── Run ──

console.log('@rararulab/style build:');
buildCSS();
buildTerminal();
buildTUI();
buildCLI();
buildPages();
console.log('\nDone.');
